routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
 Route::get('/table', function (){
    return view('table');
 });

 Route::get('/form', function (){
    return view('form');
 });

Route::get('/cv', function (){
    return view('cv');

});

Route::get('/bootstrap', function (){
    return view('bootstrap');

});
Route::get('/grid', function (){
    return view('grid');
});
Route::get('/java', function (){
    return view('java');
});

Route::get('/alert', function (){
    return view('alert');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['as'=>'admin.', 'middleware' => ['auth', 'admin'], 'prefix' => 'admin' ], function (){
    Route::get('/dashboard', 'AdminController@dashboard')->name('dashboard');

    Route::get('categories/{category}/remove', 'CategoriesController@remove')->name('categories.remove');
    Route::get('categories/trash', 'CategoriesController@trash')->name('categories.trash');
    Route::get('categories/recover/{id}', 'CategoriesController@recoverCat')->name('categories.recover');

    Route::get('votes/trash', 'VotesController@trash')->name('votes.trash');
    Route::get('votes/{vote}/remove', 'VotesController@remove')->name('votes.remove');
    Route::get('votes/restore/{id}', 'VotesController@restore')->name('votes.restore');
    Route::get('votes/show', 'VotesController@show')->name('votes.show');

    Route::get('articles/trash', 'ArticleController@trash')->name('articles.trash');
    Route::get('articles/{article}/remove', 'ArticleController@remove')->name('articles.remove');
    Route::get('articles/restore/{id}', 'ArticleController@restore')->name('articles.restore');

    Route::get('tags/article', 'TagsController@show');
    Route::get('tags/show', 'TagsController@articleShow');
    Route::post('tags/search', 'TagsController@search');

    Route::resource('products', 'ProductController');
    Route::resource('categories', 'CategoriesController');
    Route::resource('votes', 'VotesController');
    Route::resource('articles', 'ArticleController');
    Route::resource('tags', 'TagsController');


});

Route::get('logout', 'Auth\LoginController@logout', function () {
    return abort(404);
});

app/Vote.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @method static create(array $array)
 * @method static where(string $string, $id)
 * @method static findorfail($id)
 */
class Vote extends Model
{
    use SoftDeletes;
    protected $guarded= [];
    protected $dates = ['deleted_at'];

}

app/Http/Controllers/VotesController.php
<?php

namespace App\Http\Controllers;

use App\Vote;
use Illuminate\Http\Request;

class VotesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $votes = Vote::all();
        return view('admin.votes.index', compact('votes'));
    }
    public function view()
    {
        return view('admin.votes.view');
    }
    public function trash()
    {
        $votes = Vote::onlyTrashed()->paginate(10);
        //return $votes;
        return view('admin.votes.trash', compact('votes'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\sHttp\Response
     */
    public function create()
    {
        return view('admin.votes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate(
            [
                'name' => 'required | min:3',
                'CNIC' => 'required',
                'city' => 'required | min:4',
                'district' => 'required'
            ]);

        $vote = Vote::create([
            'name' => $request->name,
            'CNIC' => $request->CNIC,
            'city' => $request->city,
            'district' => $request->district,
        ]);
        $vote->save();

        return redirect('admin/votes')->with('message', 'record has been successfully added' );

    }
    /**
     * Display the specified resource.
     *
     * @param  \App\Vote  $votesiyt
     * @return \Illuminate\Http\Response
     */
    public function show(Vote $vote)
    {
        return view('admin.votes.view', compact('vote'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Vote  $votes
     * @return \Illuminate\Http\Response
     */
    public function edit(Vote $vote)
    {

       // $votes = Vote::where('id', $vote->id)->get();
       // return $votes;
            return view('admin.votes.edit')->with('vote' , $vote);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Vote  $votes
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Vote $vote)
    {
        $vote->name = $request->input("name");
        $vote->CNIC = $request->input("CNIC");
        $vote->city  = $request->input("city");
        $vote->district = $request->input("district");
        $vote->save();
            return redirect('/admin/votes')->with('message', 'Record Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Vote  $votes
     * @return \Illuminate\Http\Response
     */
    public function destroy(Vote $vote)
    {
        if($vote->forceDelete()){
            return redirect('admin.votes.index')-> with('message', 'Deleted Successfully');
        } else {
            return redirect('admin.votes.index')->with('message', 'Delete Error');
        }
    }

    public function remove(Vote $vote){

        if($vote->delete()){
            return redirect('/admin.votes.trash')->with('message', 'Deleted Successfully');
        } else {
            return redirect('/admin.votes.trash')->with('message', 'Delete Error');
        }


    }
    public function restore($id){
        $vote = Vote::withTrashed()->findorfail($id);
        if ($vote->restore()){
        return redirect('/admin/votes')->with('message', 'Recored Restored');
            } else {
            return back() -> with('message', 'Recored Restore Error');
        }
    }
}

resources/views/admin/votes/create.blade.php
@extends('admin.app')
@section('breadcrumb')
    <li class="breadcrumb-item"> <a href="{{route('admin.dashboard')}}">Dashboard</a>  </li>
    <li class="breadcrumb-item"> <a href="{{route('admin.votes.index')}}"> Votes</a> </li>
    <li class="breadcrumb-item active" aria-current="page "> Add Vote </li>
    @endsection
@section('content')
    <form action="{{route('admin.votes.store')}}" method="POST" id="myform">
        @csrf

            <div class="form-row">
                <div class="col-sm-12">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                </div>
                <div class="row d-block">
                    <div class="col-sm-12">
                        @if (session()->has('message'))
                            <div class="alert alert-success">
                                {{session('message')}}
                            </div>
                        @endif
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <label for="inputEmail4">Name:</label>
                    <input type="text" class="form-control" name="name" id="id1" placeholder="Name" ">
                </div>
                <div class="form-group col-md-6">
                    <label for="">CNIC</label>
                    <input type="text" class="form-control" name="CNIC" placeholder="CNIC #" id="id2">
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputCity" ">City</label>
                    <input type="text" class="form-control" name="city" id="inputCity">
                </div>
                <div class="form-group col-md-6">
                    <label for="inputState"  >district</label>
                    <select id="inputState" name="district" class="form-control">
                        <option selected>Choose...</option>
                        <option >SARGODHA</option>
                        <option >KARACHI</option>
                        <option >LAHORE</option>
                        <option >PESHAWAR</option>
                        <option >ISLAMABAD</option>

                    </select>
                </div>
            </div>

            <button type="submit" class="btn btn-primary">Add Record</button>
        </form>

    @endsection

resources/views/admin/votes/edit.blade.php
@extends('admin.app')
@section('breadcrumb')
    <li class="breadcrumb-item"> <a href="{{route('admin.dashboard')}}">Dashboard</a> </li>
    <li class="breadcrumb-item"> <a href="{{route('admin.votes.index')}}">Votes</a> </li>
    <li class="breadcrumb-item active" aria-current="page"> Edit Votes</li>
    @endsection
@section('content')
    <form action="{{route('admin.votes.update', $vote->id)}}" method="POST">
        @csrf
        @method('PUT')
        <div class="form-row">
            <div class="col-sm-12">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
            </div>
            <div class="row d-block">
                <div class="col-sm-12">
                    @if (session()->has('message'))
                        <div class="alert alert-success">
                            {{session('message')}}
                        </div>
                    @endif
                </div>
            </div>
            <div class="form-group col-md-6">
                <label for="inputEmail4">Name:</label>
                <input type="text" class="form-control" value="{{$vote->name}}" name="name" id="" placeholder="Name" ">
            </div>
            <div class="form-group col-md-6">
                <label for="">CNIC</label>
                <input type="text" class="form-control" value="{{$vote->CNIC}}" name="CNIC" placeholder="CNIC #" >
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="inputCity" ">City</label>
                <input type="text" class="form-control" value="{{$vote->city}}" name="city" id="inputCity">
            </div>
            <div class="form-group col-md-6">
                <label for="inputState"  >district</label>
                <select id="inputState" name="district" class="form-control">
                    <option selected>Choose...</option>
                    <option >SARGODHA</option>
                    <option >KARACHI</option>
                    <option >lAHORE</option>
                    <option >PESHAWAR</option>
                    <option >ISLAMABAD</option>

                </select>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Edit Record</button>
    </form>

@endsection

resources/views/admin/votes/index.blade.php
@extends('admin.app')
@section('breadcrumb')
    <li class="breadcrumb-item"> <a href="{{route('admin.dashboard')}}"> Dashboard </a> </li>
    <li class="breadcrumb-item active" aria-current="page"> Votes </li>
    @endsection
@section('content')
    <div class="row">
        <div class="col-6">
            <h2>
                Votes Record
            </h2>
        </div>

        <div class="row d-block">
            <div class="col-sm-12">
                @if (session()->has('message'))
                    <div class="alert alert-success">
                        {{session('message')}}
                    </div>
                @endif
            </div>
        </div>
        <div class="col-3">
            <a href="/admin/votes/create" class="btn btn-success float-right"> Add Record  </a>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>#</th>
                    <th>name </th>
                    <th>CNIC</th>
                    <th>city</th>
                    <th>district</th>
                    <th> Action </th>

                </tr>
                </thead>
                <tbody>
                @if($votes)
                    @foreach($votes as $vote)
                        <tr>
                            <td> {{$vote->id}}</td>
                            <td>
                                {{$vote->name}}</td>
                            <td> {{$vote->CNIC}} </td>
                            <td> {{$vote->city}} </td>
                            <td> {{$vote->district}} </td>
                            <td> <a class="btn btn-success" href="{{route('admin.votes.edit', $vote->id)}}" > Edit</a> |
                                <a class="btn btn-info" href="{{route('admin.votes.show', $vote->id)}}" > View </a>|
                                <a class="btn btn-warning" href="{{route('admin.votes.trash', $vote->id)}}" > trash </a> |
                                <a class="btn btn-danger " href="{{route('admin.votes.remove', $vote->id)}}">Delete</a>

                            </td>

                        </tr>
                    @endforeach
                @endif
                </tbody>
            </table>
        </div>
    </div>

@endsection
@section('scripts')
    <script type="text/javascript">
        function deleteConfirmed(id) {
            let choice = confirm('are you sure, you want to delete this message');
            if (choice){
                document.getElementById('delete-category-'+id).submit();
            }
        }
    </script>
@endsection

resources/views/admin/votes/trash.blade.php
@extends('admin.app')
@section('breadcrumb')
    <li class="breadcrumb-item " ><a href="{{route('admin.dashboard')}}">Dashboard </a></li>
    <li class="breadcrumb-item"><a href="{{route('admin.votes.index')}}">Votes</a> </li>
    <li class="breadcrumb-item active" aria-current="page">Trashed Vote</li>

@endsection
@section('content')
    <div class="row">
        <div class="col-6">
            <h2>
                Votes
            </h2>
        </div>
        <div class="row d-block">
            <div class="col-sm-12">
                @if (session()->has('message'))
                    <div class="alert alert-success">
                        {{session('message')}}
                    </div>
                @endif
            </div>
        </div>
        <div class="col-3">
            <a href="/admin/votes/create" class="btn btn-success float-right"> Add Category  </a>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>#</th>
                    <th>name </th>
                    <th>CNIC</th>
                    <th>city</th>
                    <th>district</th>
                    <th> Action </th>

                </tr>
                </thead>
                <tbody>
                @if($votes)
                    @foreach($votes as $vote)
                        <tr>
                            <td> {{$vote->id}}</td>
                            <td>
                                {{$vote->name}}</td>
                            <td> {{$vote->CNIC}} </td>
                            <td> {{$vote->city}} </td>
                            <td> {{$vote->district}} </td>
                            <td><a class="btn btn-info btn-sm" href="{{route('admin.votes.restore',$vote->id)}}">Restore</a> |
                                <a class="btn btn-danger btn-sm" href="javascript:;" onclick="deleteConfirmed('{{$vote->id}}')">Delete</a>
                                <form id="delete-category-{{$vote->id}}" action="#" method="POST" style="display: none;">
                                @method('DELETE')
                                @csrf
                            </td>
                        </tr>
                    @endforeach
                @else
                    <tr>
                        <td colspan="4"> No Categories Found ... </td>
                    </tr>
                @endif
                </tbody>
            </table>
        </div>
    </div>


@endsection
@section('scripts')
    <script type="text/javascript">
        function deleteConfirmed(id) {
            let choice = confirm('are you sure, you want to delete this message');
            if (choice){
                document.getElementById('delete-votes-'+id).submit();
            }
        }
    </script>
@endsection

resources/views/admin/votes/view.blade.php
@extends('admin.app')
@section('breadcrumb')
    <li class="breadcrumb-item " ><a href="{{route('admin.dashboard')}}">Dashboard </a></li>
    <li class="breadcrumb-item"><a href="{{route('admin.votes.index')}}">Votes</a> </li>
    <li class="breadcrumb-item active" aria-current="page">View Vote</li>

@endsection
@section('content')

<div class="container">
    <h2>VIEW MODAL</h2>
        <li> {{$vote->name}}</li>
        <li> {{$vote->CNIC}}</li>
        <li> {{$vote->city}}</li>
        <li> {{$vote->district}}</li>

</div>

@endsection