routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
 Route::get('/table', function (){
    return view('table');
 });

 Route::get('/form', function (){
    return view('form');
 });

Route::get('/cv', function (){
    return view('cv');

});

Route::get('/bootstrap', function (){
    return view('bootstrap');

});
Route::get('/grid', function (){
    return view('grid');
});
Route::get('/java', function (){
    return view('java');
});

Route::get('/alert', function (){
    return view('alert');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['as'=>'admin.', 'middleware' => ['auth', 'admin'], 'prefix' => 'admin' ], function (){
    Route::get('/dashboard', 'AdminController@dashboard')->name('dashboard');

    Route::get('categories/{category}/remove', 'CategoriesController@remove')->name('categories.remove');
    Route::get('categories/trash', 'CategoriesController@trash')->name('categories.trash');
    Route::get('categories/recover/{id}', 'CategoriesController@recoverCat')->name('categories.recover');

    Route::get('votes/trash', 'VotesController@trash')->name('votes.trash');
    Route::get('votes/{vote}/remove', 'VotesController@remove')->name('votes.remove');
    Route::get('votes/restore/{id}', 'VotesController@restore')->name('votes.restore');
    Route::get('votes/show', 'VotesController@show')->name('votes.show');

    Route::get('articles/trash', 'ArticleController@trash')->name('articles.trash');
    Route::get('articles/{article}/remove', 'ArticleController@remove')->name('articles.remove');
    Route::get('articles/restore/{id}', 'ArticleController@restore')->name('articles.restore');

    Route::get('tags/article', 'TagsController@show');
    Route::get('tags/show', 'TagsController@articleShow');
    Route::post('tags/search', 'TagsController@search');

    Route::resource('products', 'ProductController');
    Route::resource('categories', 'CategoriesController');
    Route::resource('votes', 'VotesController');
    Route::resource('articles', 'ArticleController');
    Route::resource('tags', 'TagsController');


});

Route::get('logout', 'Auth\LoginController@logout', function () {
    return abort(404);
});

app/Article.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @method static pagination(int $int)
 * @method static paginate(int $int)
 * @method static latest(string $string)
 * @method static find($id)
 * @method static where(string $string, string $string1, string $string2)
 * @method static whereIn(string $string, string $string1, array $array)
 */
class Article extends Model
{
    use SoftDeletes;
    protected $guarded = [];
    protected $dates = ['deleted_at',  'published_at'];


    public function setPublishedAtAttribute($date){
        $this->attributes['published_at'] = Carbon::createFromFormat('Y-m-d', $date)->toDateTimeString();
    }
    public function scopePublished($query){
        $query->where('published_at', '<=' , Carbon::now());
    }

    public function scopeunPublished($query){
        $query->where('published_at', '>' , Carbon::now());
    }
    public function tag(){
        return $this->belongsToMany(Tag::class);
    }

    public function getFromDateAttribute($value) {
        return \Carbon\Carbon::parse($value)->format('Y-m-d');
    }

}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use App\Tag;
use Carbon\Carbon;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $articles = Article::latest('published_at')->published()->get();
        return view('admin.articles.index', compact('articles'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function trash()
    {
        $articles = Article::onlyTrashed()->paginate(2);
        return view('admin.articles.trash', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tags = Tag::all();
        return view('admin.articles.create', compact('tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
               'title' => 'required| min:3',
               'description' => 'required| min:5'
         ]);

        $article = Article::create([
            'title' => $request->title,
            'description' => $request->description,
            'published_at' => $request->published_at
        ]);

        $article->tag()->attach($request->tag_id);
        return redirect('/admin/articles')->with('message', 'Article Published');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Article  $atricle
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
            
        return view('/admin/articles/view')->with('article', $article);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Article $article
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        return view('/admin/articles/edit')->with('article', $article);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param Article $article
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Article $article)
    {
        $article->title = $request->input('title');
        $article->description = $request->input('description');
        $article->published_at = $request->input('published_at');
        $article->save();
        return redirect('/admin/articles')->with('message', 'Article updated');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Article $article
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        if ($article->forceDelete()){
            return redirect('/admin.index')->with('message', 'Record permanently deleted');
        }
        else{
            return redirect('admin.index')->with('message', 'Record deletion error');
        }
    }
     public function remove(Article $article)
    {
    if ($article->delete()){
        return redirect('/admin/articles/trash')->with('message', 'Record Trashed');
        }
    else{
        return redirect('/admin/articles/trash')->with('message', 'Record  Error');
    }

    }

    public function restore($id){
        $article =  Article::withTrashed()->findOrFail($id);

        if ($article->restore()){

            return redirect('/admin/articles')->with('message', 'Record Restore');
        }
        else {

            return redirect('/admin/articles')->with('message', 'Record restore error');
        }
    }
}

resources/views/admin/articles/create.blade.php
@extends('admin.app')
@section('breadcrumb')
    <li class="breadcrumb-item " ><a href="{{route('admin.dashboard')}}">Dashboard </a></li>
    <li class="breadcrumb-item "><a href="{{route('admin.articles.index')}}">Articles </a></li>
    <li class="breadcrumb-item active" aria-current="page"> Add Article</li>
@endsection
@section('content')

    <form action="{{route('admin.articles.store')}}" method="POST" id="myform">
        @csrf

        <div class="form-group row">
            <div class="col-sm-12">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
            </div>

            <div class="col-sm-12">
                @if (session()->has('message'))
                    <div class="alert alert-success">
                        {{session('message')}}
                    </div>
                @endif
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-12">
                <label class="form-control-label" > <strong> Title: </strong></label>
                <input type="text" class="form-control " name="title"  placeholder="Enter title" >

            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-12">
            <label class="control-label " > <strong>Description: </strong></label>
                <textarea name="description" id="editor" class="form-control" rows="10" cols="80"></textarea>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-12">
            <label class="control-label " > <strong>Published: </strong></label>
                <input type="date" class="form-control" name="published_at" value="date(m-d-y)">
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-12">
            <label class="form-control-label"> <strong>  Select Tag:</strong> </label>
            <select  name="tag_id[]" id="tag_id" class="form-control" multiple >
                    <option value="0"> Top Level</option>
                    @foreach($tags as $tag)
                        <option value="{{$tag->id}}">
                            {{$tag->title}}   </option>
                    @endforeach

            </select>
        </div>
        </div>
        <div class="form-group row">
                    <button type="submit" id="btn" class="btn btn-primary"> Add Article </button>
            </div>


        @endsection
    </form>
@section('scripts')
    <script type="text/javascript">

        ClassicEditor.create(document.querySelector('#editor'), {
            toolbar: ['Heading', 'Link', 'bold', 'italic', 'bulletedList', 'undo', 'redo'],
        }).then(editor => {
            console.log(editor);
        })
            .catch(error => {
                console.error(error);
            });


        $('#document').ready(function() {
            $(#myform).submit(function(event) {
                event.preventDefault();
                var post_url = $(this).attr("action");
                var method = $(this).attr("method");
                var form = $(this).serialize();
            });

                $.ajax({
                   url: post_url,
                   type: method,
                    data: form,
                }).done(function(response) {
                    $("#server-result").html(response);
                });

            });
            $('#tag_id').select2({
                placeholder: "select a tag",
            });
        });

    </script>
@endsection

resources/views/admin/articles/edit.blade.php
@extends('admin.app')
@section('breadcrumb')
    <li class="breadcrumb-item " ><a href="{{route('admin.dashboard')}}">Dashboard </a></li>
    <li class="breadcrumb-item "><a href="{{route('admin.articles.index')}}">Articles </a></li>
    <li class="breadcrumb-item active" aria-current="page"> Edit Article</li>
@endsection
@section('content')

    <form action="{{route('admin.articles.update', $article->id)}}" method="POST">
        @method('PUT')
        @csrf

        <div class="form-group">
            <div class="col-sm-12">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
            </div>

            <div class="col-sm-12">
                @if (session()->has('message'))
                    <div class="alert alert-success">
                        {{session('message')}}
                    </div>
                @endif
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-12">
                <label class="form-control-label" > <strong> Title: </strong></label>
                <input type="text" class="form-control " name="title" value="{{$article->title}}" placeholder="Enter title" >
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-12">
            <label class="control-label " > <strong>Description: </strong></label>
                <textarea name="description" id="editor" class="form-control" rows="10" cols="80"> {!! $article->description !!} </textarea>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-12">
            <label class="control-label " > <strong>Published: </strong></label>
                    <input type="date" class="form-control" name="published_at" value="{{$article->getFromDateAttribute($article->published_at)}}">
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-12">
                    <label class="form-control-label"> <strong>  Select Tag:</strong> </label>
                <select  name="tag_id[]" id="tag_id" class="form-control" value="" multiple >
                    <option value="0"> Top Level</option>
                    @foreach($tags as $tag)
                        <option value="{{$tag->id}}">
                            {{$tag->title}}   </option>
                    @endforeach
                </select>
            </div>
        </div>



                <div class="form-group row">
                    <button type="submit"  class="btn btn-primary"> Edit Article </button>
                </div>

        @endsection
    </form>
@section('scripts')
    <script type="text/javascript">

        ClassicEditor.create(document.querySelector('#editor'), {
            toolbar: ['Heading', 'Link', 'bold', 'italic', 'bulletedList', 'undo', 'redo'],
        }).then(editor => {
            console.log(editor);
        })
            .catch(error => {
                console.error(error);
            });
        $('#document').ready(function () {
            $('#tag_id').select2({
                placeholder: "select a tag",
            });
        });

    </script>
@endsection

resources/views/admin/articles/index.blade.php
@extends('admin.app')
@section('breadcrumb')
    <li class="breadcrumb-item " ><a href="{{route('admin.dashboard')}}">Dashboard </a></li>
    <li class="breadcrumb-item active" aria-current="page"> Articles </li>
    @endsection
@section('content')
    <div class="row">
        <div class="col-6">
            <h2>
                Articles
            </h2>
        </div>
        <div class="row d-block">
            <div class="col-sm-12">
                @if (session()->has('message'))
                    <div class="alert alert-success">
                        {{session('message')}}
                    </div>
                @endif
            </div>
        </div>
        <div class="col-3">
            <a href="{{route('admin.articles.create')}}" class="btn btn-success float-right"> Add Article  </a>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>#</th>
                    <th>title </th>
                    <th>Description</th>
                    <th> Published at</th>
                    <th> Tags </th>
                    <th> Action </th>
                </tr>
                </thead>
    <tbody>
    @if($articles)
        @foreach($articles as $article)
        <tr>
            <td>{{$article->id}}</td>
            <td> {{$article->title}} </td>
            <td> {{$article->description}}</td>
            <td> {{$article->published_at}}</td>
            <td> @if($article->tag()->count() > 0)
                  @foreach($article->tag as $tag)
                      {{$tag->title}}
                      @endforeach

            @endif
            </td>
            <td> <a class="btn btn-primary" href="{{route('admin.articles.edit', $article->id)}}" >Edit </a> |
                <a class="btn btn-info" href="{{route('admin.articles.trash', $article->id)}}"> Trash</a> |
                <a class="btn btn-success" href="{{route('admin.articles.show', $article->id)}}"> view </a>
                <a class="btn btn-danger" href="{{route('admin.articles.remove', $article->id)}}" > Delete </a> |
                 </td>
            <form id="delete-category-{{$article->id}}" action="{{ route('admin.articles.destroy', $article->id) }}" method="POST" style="display: none;">
            @method('DELETE')
            @csrf
        </tr>
        @endforeach
        @endif
    </tbody>
            </table>
        </div>
    </div>
    @endsection

@section('scripts')
    <script type="text/javascript">
        function deleteConfirmed(id) {
            let choice = confirm('are you sure, you want to delete this message');
            if (choice){
                document.getElementById('delete-category-'+id).submit();
            }
        }
    </script>
@endsection

resources/views/admin/articles/trash.blade.php
@extends('admin.app')
@section('breadcrumbs')
    <li class="breadcrumb"> <a href="{{route('admin.dashboard')}}"> Dashboard </a> </li>
    <li class="breadcrumb active" aria-current="page"> article </li>
@endsection
@section('content')
    <div class="row">
        <div class="col-6">
            <h2>
                Articles
            </h2>
        </div>
        <div class="row d-block">
            <div class="col-sm-12">
                @if (session()->has('message'))
                    <div class="alert alert-success">
                        {{session('message')}}
                    </div>
                @endif
            </div>
        </div>
        <div class="col-3">
            <a href="{{route('admin.articles.create')}}" class="btn btn-success float-right"> Add Article  </a>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>#</th>
                    <th>title </th>
                    <th>Description</th>
                    <th> Published at</th>
                    <th> Action </th>
                </tr>
                </thead>
                <tbody>
                @if($articles)
                    @foreach($articles as $article)
                        <tr>
                            <td>{{$article->id}}</td>
                            <td> {{$article->title}} </td>
                            <td> {{$article->description}}</td>
                            <td> {{$article->published_at}}</td>
                            <td> <a class="btn btn-primary" href="{{route('admin.articles.restore', $article->id)}}" >Restore </a> |
                                <a class="btn btn-danger btn-sm" href="javascript:;" onclick="deleteConfirmed('{{$article->id}}')">Delete</a>
                                <form id="delete-category-{{$article->id}}" action="{{route('admin.articles.destroy', $article->id)}}" method="POST">
                                    @method('DELETE')
                                    @csrf
                                </form>
                            </td>
                        </tr>
                    @endforeach
                @endif
                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('scripts')
    <script type="text/javascript">
        function deleteConfirmed(id) {
            let choice = confirm('are you sure, you want to delete this message');
            if (choice){
                document.getElementById('delete-category-'+id).submit();
            }
        }
    </script>
@endsection

resources/views/admin/articles/view.blade.php
@extends('admin.app')
@section('breadcrumbs')
    <li class="breadcrumb"> <a href="{{route('admin.dashboard')}}"> Dashboard </a> </li>
    <li class="breadcrumb active" aria-current="page"> article </li>
    @endsection
@section('content')
    <div class="row">
        <div class="col-6">
            <h2>
              View  Articles
            </h2>
        </div>

        <div class="col-3">
            <a href="{{route('admin.articles.create')}}" class="btn btn-success float-right"> Add Article  </a>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>#</th>
                    <th>title </th>
                    <th>Description</th>
                    <th> Published at</th>
                    <th> Action </th>
                </tr>
                </thead>
    <tbody>

        <tr>
            <td>{{$article->id}}</td>
            <td> {{$article->title}} </td>
            <td> {{$article->description}}</td>
            <td> {{$article->published_at}}</td>
            <td> <a class="btn btn-danger" href="{{route('admin.articles.remove', $article->id)}}" > Delete </a>
                 </td>

        </tr>

    </tbody>
            </table>
        </div>
    </div>
    @endsection