routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
 Route::get('/table', function (){
    return view('table');
 });

 Route::get('/form', function (){
    return view('form');
 });

Route::get('/cv', function (){
    return view('cv');

});

Route::get('/bootstrap', function (){
    return view('bootstrap');

});
Route::get('/grid', function (){
    return view('grid');
});
Route::get('/java', function (){
    return view('java');
});

Route::get('/alert', function (){
    return view('alert');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['as'=>'admin.', 'middleware' => ['auth', 'admin'], 'prefix' => 'admin' ], function (){
    Route::get('/dashboard', 'AdminController@dashboard')->name('dashboard');

    Route::get('categories/{category}/remove', 'CategoriesController@remove')->name('categories.remove');
    Route::get('categories/trash', 'CategoriesController@trash')->name('categories.trash');
    Route::get('categories/recover/{id}', 'CategoriesController@recoverCat')->name('categories.recover');

    Route::get('votes/trash', 'VotesController@trash')->name('votes.trash');
    Route::get('votes/{vote}/remove', 'VotesController@remove')->name('votes.remove');
    Route::get('votes/restore/{id}', 'VotesController@restore')->name('votes.restore');
    Route::get('votes/show', 'VotesController@show')->name('votes.show');

    Route::get('articles/trash', 'ArticleController@trash')->name('articles.trash');
    Route::get('articles/{article}/remove', 'ArticleController@remove')->name('articles.remove');
    Route::get('articles/restore/{id}', 'ArticleController@restore')->name('articles.restore');

    Route::get('tags/article', 'TagsController@show');
    Route::get('tags/show', 'TagsController@articleShow');
    Route::post('tags/search', 'TagsController@search');

    Route::resource('products', 'ProductController');
    Route::resource('categories', 'CategoriesController');
    Route::resource('votes', 'VotesController');
    Route::resource('articles', 'ArticleController');
    Route::resource('tags', 'TagsController');


});

Route::get('logout', 'Auth\LoginController@logout', function () {
    return abort(404);
});

app/Category.php
<?php

namespace App;

use App\Http\Controllers\CategoryController;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @method static paginate(int $int)
 */
class Category extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    protected $guarded = [];

    public function product(){

        return $this->belongsToMany(Product::class);
    }
    public function children(){
        return $this->belongsToMany(Category::class,'category_parent', 'category_id',
            'parent_id');
    }


}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use foo\bar;
use Illuminate\Http\Request;
use SebastianBergmann\CodeCoverage\TestFixture\C;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::paginate(3);
        return view('admin.categories.index', compact('categories'));
    }
    public function trash()
    {
        $categories = Category::onlyTrashed()->paginate(3);
        return view('admin.categories.trash', compact('categories'));
    }
    public function create()
    {
       $categories = Category::all();
        return view('admin.categories.create')->with(['catagories'=> $categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required | min:5',
            'description' => 'required'
        ]);
         $categories = Category::create([
           'title' => request('title'),
           'description' => request('description')
        ]);
         $categories->children()->attach($request->parent_id);
        return back();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param Category $category
     * @return void
     */
    public function update(Request $request, Category $category)
    {
        $category->title = $request->title;
        $category->description = $request->description;
        $category->save();
        $category->children()->detach();
        $category->children()->attach($request->parent_id);
        return  back()->with('message', 'record successfully updated');
    }

    /**
     * Display the specified resource.
     *
     * @param Category $category
     * @return void
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Category $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $categories = Category::with('Children')->where('id' , $category->id)->get();
        //return print_r($categories[0]->children);
        return view('admin.categories.create', ['categories' =>$categories, 'category' => $category]);
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category $categories
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function recoverCat($id)
    {
        $category = Category::withTrashed()->findOrFail($id);
        if($category->restore()) {
            return back()->with('message', 'Restore Successfully');

        } else {
            return back()->with('messege','Restore Error');
        }
    }
    public function destroy(Category $category)
{
    if($category->children()->detach() && $category->forceDelete()) {
        return back()->with('message', 'Deleted Successfully');

    } else {
        return back()->with('messege','Delete Error');
    }
}

    public function remove(Category $category)
    {
        if($category->Delete()) {
            return back()->with('message', 'Trashed Successfully');

        } else {
            return back()->with('messege','Trashed Error');
        }
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.app')
@section('breadcrumb')
    <li class="breadcrumb-item " ><a href="{{route('admin.dashboard')}}">Dashboard </a></li>
    <li class="breadcrumb-item "><a href="{{route('admin.categories.index')}}">categories </a></li>
    <li class="breadcrumb-item active" aria-current="page"> Add/Edit Category</li>
@endsection
@section('content')

    <form action="@if(isset($category)) {{route('admin.categories.update', $category->id)}}
        @else {{route('admin.categories.store')}} @endif" method="POST" id="formid">
        @csrf
        @if(isset($category))
            @method('PUT')
            @endif
        <div class="form-group row">
        <div class="col-sm-12">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        </div>

            <div class="col-sm-12">
                @if (session()->has('message'))
                    <div class="alert alert-success">
                        {{session('message')}}
                    </div>
                @endif
            </div>
        </div>
        <div class="form-group" >
            <div class="col-sm-12">
            <label class="form-control-label" > <strong> Title: </strong></label>
                <input type="text" class="form-control " name="title"  placeholder="Enter title" value="{{@$category->title}}">
                <p class="small"> {{config('app,url')}} <span id="url"></span> </p>
                <input type="hidden" name="slug" id="slug" value="">
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-12">
            <label class="form-control-label"> <strong>  Description: </strong></label>

                        <textarea name="description" id="editor" class="form-control" rows="10" cols="80">{!! @$category->description !!}</textarea>
            </div>
            </div>

            <div class="col-sm-12">
                <label class="form-control-label"> <strong>  Select Category:</strong> </label>
                <select  name="parent_id[]" id="parent_id" class="form-control" multiple >
                    @if(isset($categories))
                        <option value="0"> Top Level</option>
                        @foreach($categories[0]->children as $category)
                            <option value="{{$category['id']}}">
                            {{$category['title']}}   </option>
                        @endforeach
                        @endif
                </select>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-12">
                <div class="checkbox">
                    <label><input type="checkbox" > <b> Remember me </b></label>
                </div>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-12">
                @if(isset($category))
                    <button type="submit"  class="btn btn-primary"> Edit Category </button>
                @else
                    <button type="submit"  class="btn btn-primary"> Add Category </button>
                @endif
            </div>
        </div>

        @endsection
    </form>
    @section('scripts')
        <script type="text/javascript">

                ClassicEditor.create(document.querySelector('#editor'), {
                    toolbar: ['Heading', 'Link', 'bold', 'italic', 'bulletedList', 'undo', 'redo'],
                }).then(editor => {
                    console.log(editor);
                })
                    .catch(error => {
                        console.error(error);
                    });
                $('#txturl').on('keyup', function () {
                    var url = slugify($(this).val());
                    $('#url').html(url);
                    $('#slug').var(url);
                });
                $('#document').ready(function () {

                });
                    $('#parent_id').select2({
                        placeholder: "select a parent category",
                    });
                });


                $('.datepicker').datepicker();

        </script>
    @endsection

resources/views/admin/categories/index.blade.php
@extends('admin.app')
@section('breadcrumb')
    <li class="breadcrumb-item " ><a href="{{route('admin.dashboard')}}">Dashboard </a></li>
    <li class="breadcrumb-item active" aria-current="page">categories</li>

@endsection
@section('content')
<div class="row">
    <div class="col-6">
        <h2>
            Categories
        </h2>
    </div>
    <div class="row d-block">
        <div class="col-sm-12">
            @if (session()->has('message'))
                <div class="alert alert-success">
                    {{session('message')}}
                </div>
            @endif
        </div>
    </div>
    <div class="col-3">
        <a href="/admin/categories/create" class="btn btn-success float-right"> Add Category  </a>
    </div>
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
            <tr>
                <th>#</th>
                <th>title </th>
                <th>description</th>
                <th>categories</th>
                <th> Date Created</th>
                <th> Action </th>
            </tr>
            </thead>
            <tbody>
            @if($categories)
                @foreach($categories as $category)
            <tr>
                <td> {{$category->id}}</td>
                <td>{{$category->title}}</td>
                <td>{!! $category->description !!}</td>
                <td>
                    @if($category->children()->count()> 0)
                        @foreach($category->children as $children)
                            {{$children->title}}
                            @endforeach
                    @else
                        {{"Parent Category"}}
                        @endif
                </td>
                <td>{{$category->created_at}}</td>
                <td><a class="btn btn-info btn-sm" href="{{route('admin.categories.edit',$category->id)}}">Edit</a> |
                    <a class="btn btn-success btn-sm" href="{{route('admin.categories.trash',$category->id)}}"> Trash </a> |
                    <a class="btn btn-danger btn-sm" href="javascript:;" onclick="deleteConfirmed('{{$category->id}}')">Delete</a>
                    <form id="delete-category-{{$category->id}}" action="{{ route('admin.categories.destroy', $category->id) }}" method="POST" style="display: none;">
                    @method('DELETE')
                    @csrf
                </td>
            </tr>
            @endforeach
            @else
                <tr>
                    <td colspan="4"> No Categories Found ... </td>
                </tr>
                @endif
            </tbody>
        </table>
            </div>
</div>

<div class="row">
    <div class="col-md-12">
        {{$categories->links()}}
    </div>
</div>
@endsection
@section('scripts')
    <script type="text/javascript">
        function deleteConfirmed(id) {
            let choice = confirm('are you sure, you want to delete this message');
            if (choice){
                document.getElementById('delete-category-'+id).submit();
            }
        }
    </script>
    @endsection

resources/views/admin/categories/trash.blade.php
@extends('admin.app')
@section('breadcrumb')
    <li class="breadcrumb-item " ><a href="{{route('admin.dashboard')}}">Dashboard </a></li>
    <li class="breadcrumb-item" ><a href="{{route('admin.categories.index')}}"> categories </a></li>
    <li class="breadcrumb-item active" aria-current="page">trash</li>

@endsection
@section('content')
    <div class="row">
        <div class="col-6">
            <h2>
                Categories
            </h2>
        </div>
        <div class="row d-block">
            <div class="col-sm-12">
                @if (session()->has('message'))
                    <div class="alert alert-success">
                        {{session('message')}}
                    </div>
                @endif
            </div>
        </div>
        <div class="col-3">
            <a href="/admin/votes/create" class="btn btn-success float-right"> Add Category  </a>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>#</th>
                    <th>title </th>
                    <th>description</th>
                    <th>categories</th>
                    <th> Date Created</th>
                    <th> Action </th>
                </tr>
                </thead>
                <tbody>
                @if($categories)
                    @foreach($categories as $category)
                        <tr>
                            <td> {{$category->id}}</td>
                            <td>{{$category->title}}</td>
                            <td>{!! $category->description !!}</td>
                            <td>
                                @if($category->children()->count()> 0)
                                    @foreach($category->children as $children)
                                        {{$children->title}}
                                    @endforeach
                                @else
                                    {{"Parent Category"}}
                                @endif
                            </td>
                            <td>{{$category->created_at}}</td>
                            <td><a class="btn btn-success btn-sm" href="/admin/categories/recover/{{$category->id}}" >Restore</a> |
                                <a class="btn btn-danger btn-sm" href="javascript:;" onclick="deleteConfirmed('{{$category->id}}')" >Delete</a>
                                <form id="delete-category-{{$category->id}}" action="{{route('admin.categories.destroy', $category->id)}}" method="POST">
                                @method('DELETE')
                                @csrf
                                </form>
                            </td>

                        </tr>
                    @endforeach
                @else
                    <tr>
                        <td colspan="4"> No Categories Found ... </td>
                    </tr>
                @endif
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            {{$categories->links()}}
        </div>
    </div>
@endsection
@section('scripts')
    <script type="text/javascript">
        function deleteConfirmed(id) {
            let choice = confirm('are you sure, you want to delete this message');
            if (choice){
                document.getElementById('delete-category-'+id).submit();
            }
        }
    </script>
@endsection