routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
 Route::get('/table', function (){
    return view('table');
 });

 Route::get('/form', function (){
    return view('form');
 });

Route::get('/cv', function (){
    return view('cv');

});

Route::get('/bootstrap', function (){
    return view('bootstrap');

});
Route::get('/grid', function (){
    return view('grid');
});
Route::get('/java', function (){
    return view('java');
});

Route::get('/alert', function (){
    return view('alert');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['as'=>'admin.', 'middleware' => ['auth', 'admin'], 'prefix' => 'admin' ], function (){
    Route::get('/dashboard', 'AdminController@dashboard')->name('dashboard');

    Route::get('categories/{category}/remove', 'CategoriesController@remove')->name('categories.remove');
    Route::get('categories/trash', 'CategoriesController@trash')->name('categories.trash');
    Route::get('categories/recover/{id}', 'CategoriesController@recoverCat')->name('categories.recover');

    Route::get('votes/trash', 'VotesController@trash')->name('votes.trash');
    Route::get('votes/{vote}/remove', 'VotesController@remove')->name('votes.remove');
    Route::get('votes/restore/{id}', 'VotesController@restore')->name('votes.restore');
    Route::get('votes/show', 'VotesController@show')->name('votes.show');

    Route::get('articles/trash', 'ArticleController@trash')->name('articles.trash');
    Route::get('articles/{article}/remove', 'ArticleController@remove')->name('articles.remove');
    Route::get('articles/restore/{id}', 'ArticleController@restore')->name('articles.restore');

    Route::get('tags/article', 'TagsController@show');
    Route::get('tags/show', 'TagsController@articleShow');
    Route::post('tags/search', 'TagsController@search');

    Route::resource('products', 'ProductController');
    Route::resource('categories', 'CategoriesController');
    Route::resource('votes', 'VotesController');
    Route::resource('articles', 'ArticleController');
    Route::resource('tags', 'TagsController');


});

Route::get('logout', 'Auth\LoginController@logout', function () {
    return abort(404);
});

resources/views/admin/partials/navigation.blade.php
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{{route('admin.dashboard')}}">Company name</a>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <a class="nav-link" href="#">Sign out</a>
        </li>
    </ul>
</nav>

<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link  @if(request()->url() == route('admin.dashboard')) {{'active'}}  @endif"
                                href="{{route('admin.dashboard')}}">
                            <span data-feather="home"></span>
                            Dashboard <span class="sr-only">(current)</span>
                        </a>
                    </li>

                    <li class="nav-item dropdown">
                        <a id="productDropdown" class="nav-link @if(request()->url() == route('admin.products.index')) {{'active'}}@endif dropdown-toggle"
                            href="javascript:;" role ="button" data-toggle ="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span data-feather="shopping-cart"></span>
                            Products
                        </a>

                        <div class="dropdown-menu" aria-labelledby="productDropdown">

                        <a class="dropdown-item"  href="{{route('admin.products.create')}}"> Add Products </a>
                        <a class="dropdown-item"  href="{{route('admin.products.index')}}"> All Products </a>
                        <a class="dropdown-item"  href="#"> Trashed Products </a>
                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link @if(request()->url() == route('admin.categories.index')) {{'active'}} @else {{''}} @endif dropdown-toggle"
                           href="#" role ="button" data-toggle ="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span data-feather="bar-chart-2"></span>
                            Categories
                                </a>
                        <div class="dropdown-menu" aria-labelledby="categoriesDropdown">
                            <a class="dropdown-item"  href="{{route('admin.categories.create')}}"> Add Categories </a>
                            <a class="dropdown-item"  href="{{route('admin.categories.index')}}"> All Categories </a>
                            <a class="dropdown-item"  href="{{route('admin.categories.trash')}}"> Trashed Categories </a>
                        </div>
                    </li>

                    <li class="nav-item ">
                        <a class="nav-link" href="#">
                            <span data-feather="users"></span>
                            Customers
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file"></span>
                            Orders
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="layers"></span>
                            Integrations
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link  @if(request()->url() == route('admin.votes.index')) {{'active'}}  @endif dropdown-toggle"
                           href="#" role ="button" data-toggle ="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span data-feather="votes"></span>
                            Votes
                        </a>
                        <div class="dropdown-menu" aria-labelledby="VotesDropdown">
                            <a class="dropdown-item"  href="{{route('admin.votes.create')}}"> Add Votes </a>
                            <a class="dropdown-item"  href="{{route('admin.votes.index')}}"> All Votes </a>
                            <a class="dropdown-item"  href="{{route('admin.votes.trash')}}"> Trashed Votes </a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link  @if(request()->url() == route('admin.articles.index')) {{'active'}}  @endif dropdown-toggle"
                           href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span data-feather="votes"></span>
                            Articles
                        </a>
                        <div class="dropdown-menu" aria-labelledby="ArticleDropdown">
                            <a class="dropdown-item" href="{{route('admin.articles.create')}}"> Add Article</a>
                            <a class="dropdown-item" href="{{route('admin.articles.index')}}"> All Articles</a>
                            <a class="dropdown-item" href="{{route('admin.articles.trash')}}"> Trashed Articles</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('admin.tags.index')}}">
                            <span data-feather="file-text"></span>
                           Tags
                        </a>
                    </li>
                </ul>

                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span>Saved reports</span>
                    <a class="d-flex align-items-center text-muted" href="#">
                        <span data-feather="plus-circle"></span>
                    </a>
                </h6>
                <ul class="nav flex-column mb-2">
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Current month
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Last quarter
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Social engagement
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Year-end sale
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>